version: 2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: 'Run Build'
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: 'Run Test'
          command: npm run test:unit

  deploy:
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Deploy to S3'
          command: aws s3 sync dist s3://circleci-test-app

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - main
