version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Run Build'
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Run Test'
          command: npm run test:unit

  deploy:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: dist
          to: 's3://circleci-test-app'

workflows:
  build-and-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - main
